from random import randint

logo="""
   _____                       _______ _            _   _                 _               
  / ____|                     |__   __| |          | \ | |               | |              
 | |  __ _   _  ___  ___ ___     | |  | |__   ___  |  \| |_   _ _ __ ___ | |__   ___ _ __ 
 | | |_ | | | |/ _ \/ __/ __|    | |  | '_ \ / _ \ | . ` | | | | '_ ` _ \| '_ \ / _ \ '__|
 | |__| | |_| |  __/\__ \__ \    | |  | | | |  __/ | |\  | |_| | | | | | | |_) |  __/ |   
  \_____|\__,_|\___||___/___/    |_|  |_| |_|\___| |_| \_|\__,_|_| |_| |_|_.__/ \___|_|   
                                                                                          
                                                                                          
"""

EASY_LEVEL_TURNS = 10
HARD_LEVEL_TURNS = 5

def check_ans(guess, ans, turns):
 
  if guess > ans:
    print("Too high ! ")
    return turns - 1
  elif guess < ans:
    print("Too low ! ")
    return turns - 1
  else:
    print("-------------------------------------------------------------")
    print(f"\t\tYou WON the Game!\n\t\tThe Number is : {ans} ")
    print("-------------------------------------------------------------")

def set_difficulty():
  level = input("Choose a difficulty. Type 'easy' or 'hard': ")
  if level == "easy":
    return EASY_LEVEL_TURNS
  else:
    return HARD_LEVEL_TURNS

def game():
    
    print(logo)
    print("-------------------------------------------------------------")
    print("\t\tWelcome to the Number Guessing Game!")
    print("-------------------------------------------------------------")
    print("I'm thinking of a number between 1 and 100.")
    ans = randint(1, 100)
    #print(f"number generated by computer is {ans}") 

    turns = set_difficulty()
    guess = 0
    while guess != ans:
      print(f"You have {turns} attempts remaining to guess the number.")
      guess = int(input("Make a guess: "))
      turns = check_ans(guess, ans, turns)
      if turns == 0:
        print("-------------------------------------------------------------")
        print("\t\tNo Guess left !\n\t\t  You lose ! ")
        print("-------------------------------------------------------------")
        return
    
      elif guess != ans:
        print("-------------------------------------------------------------")
        print("Guess again".center(60))
    


game()